# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('org.apache.kafka', 'kafka-clients', '2.1.0')
require_jar('com.github.luben', 'zstd-jni', '1.3.7-3')
require_jar('org.slf4j', 'slf4j-api', '1.7.25')
require_jar('org.lz4', 'lz4-java', '1.5.0')
require_jar('org.xerial.snappy', 'snappy-java', '1.1.7.2')
