# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('org.apache.kafka', 'kafka-clients', '1.1.0')
require_jar('org.slf4j', 'slf4j-api', '1.7.25')
require_jar('org.lz4', 'lz4-java', '1.4')
require_jar('org.xerial.snappy', 'snappy-java', '1.1.7.1')
