# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('org.apache.kafka', 'kafka-clients', '1.0.0')
require_jar('org.apache.logging.log4j', 'log4j-slf4j-impl', '2.8.2')
require_jar('org.lz4', 'lz4-java', '1.4')
require_jar('org.xerial.snappy', 'snappy-java', '1.1.4')
require_jar('org.slf4j', 'slf4j-api', '1.7.25')
require_jar('org.apache.logging.log4j', 'log4j-api', '2.8.2')
